# Generated by Django 5.1.6 on 2025-03-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0002_remove_course_teachers_delete_courseuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='pupils', to='courses.course'),
        ),
    ]
