# Generated by Django 5.1.6 on 2025-03-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.DeleteModel(
            name='CourseUser',
        ),
    ]
