# Generated by Django 5.1.6 on 2025-03-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_video_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='teachers/photos/')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='courses.category')),
            ],
        ),
    ]
