# Generated by Django 5.1.6 on 2025-03-06 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_coursecomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_duration',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
